name: Update Submodules & Trigger CI/CD

on:
  repository_dispatch:
    types: [update_submodules]

jobs:
  update-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout SEI
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.GH_TOKEN }}

      - name: Update submodules
        run: |
          git submodule update --remote --merge
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Update submodules to latest"
          git push
