name: Deploy to Development

on:
  repository_dispatch:
    types: [submodule-updated]
    
jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - run: |
          git submodule update --remote --merge
          git commit -am "update submodules"
          git push
          